name: CI Simples

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Mensagem de sucesso
        run: echo "Deploy bem-sucedido "
